### ISSUE TITLE
k8s fails to pull image from ACR

### ISSUE THREAD

**Issue by v1r7u** [azooinmyluggage/k8s-docker-core#1]
Excuse me, for asking it here, but I didn't find a better place.
I tried to complete the [tutorial](https://blogs.msdn.microsoft.com/devops/2017/06/09/deploying-applications-to-azure-container-service/) and met an issue, that I don't know how to fix.

At the last step in Release Definition, I created k8s set command with my own docker image, but pods fail to pull this image from Azure Container Registry.
Arguments field for this step is
`image deployment/coreserverdeployment core-server=acrkubernetes.azurecr.io/docker-dotnetcore:$(Build.BuildId)`
Where "acrkubernetes" is the name of my ACR.

What I've done
* I tried to use "Secret Name" with checkbox "Force Secret Update" at VSTS task to create a docker-registry secret.
* I tried to remove all these "secrets" from VSTS (from the previous step) and create the docker-registry with k8s cli instead of them (I took ACR credentials from "Access Keys" tab at Azure Portal)
`kubectl create secret docker-registry azurecontainerreg --docker-server=SERVER --docker-username=USERNAME --docker-password=PASSWORD --docker-email=my.email@mail.com`
* I removed port 8080 and changed ACR name to my own in deployment.yaml https://github.com/azooinmyluggage/k8s-docker-core/blob/master/k8config/deployment.yaml

Every time I'm getting the same exception:
> Failed to pull image "acrkubernetes.azurecr.io/docker-dotnetcore:72": [rpc error: code = 2 desc = unknown blob, rpc error: code = 2 desc = unknown blob]

How I'm checking results.
I installed k8s cli, connected to the master node and executing 2 commands:
1) `kubectl get pods` (all pods are in ImagePullBackOff status)
2) `kubectl describe pod pod_name`
3) before starting a new iteration, I'm removing deployment `kubectl delete deployment coreserverdeployment`

Also, I tried to pull the same image with docker cli using the same credentials and it works fine. I tried it from my laptop and from master node (connected with ssh) `docker pull ....`

Do you have any ideas, what I'm doing wrong?
I will be very grateful for any help

**Comment by v1r7u** [comment]
The main problem was with VSTS Agent type. 
There are 2 sets of asp.net core docker images: one for windows, the second one - for linux. Appropriate image type is chosen automatically, based on Agent's OS. For example, if you run build process with Hosted Windows Agents - you will get docker's windows based container, which, obviously, is not applicable to be run with k8s cluster.

Therefore, in our case we solved the problem with just switching Default Agent Queue to Linux Hosted one.

Also, we had one more problem with this build process: `dotnet publish -o publish` step is creating one more folder with the name of your project inside requested "publish" directory. It was not expected behavior, therefore we spent some time to figure it out.

**Comment by goyalmohit** [comment]
Hi @v1r7u, can you please advise how did you resolve the issue for publish with it was creating one more folder with the name of the project.

It will be of great help if you can share details.

**Comment by v1r7u** [comment]
Hi, @goyalmohit !
We haven't resolved this issue anyhow. I'm afraid, it may be not possible to change this behavior (at least, we didn't find how to do it that time).
The only one advice: use the path `publish\{project_name}` later instead of just `publish`.

**Comment by goyalmohit** [comment]
Thanks @v1r7u for the prompt reply. I'll try this at my end.
